import { chromium } from '@playwright/test'
const email = process.argv[2]
const b = await chromium.launch(); const p = await b.newPage()
await p.goto('http://127.0.0.1:3100/en/register', { waitUntil: 'load' })
await p.getByText('Robotics & Drones').first().click()
await p.getByRole('button', { name: 'Next', exact: true }).click()
await p.getByLabel('Full name').fill('QTE E2E Tester')
await p.getByLabel('Mobile / WhatsApp').fill('+974 3312 3456')
await p.getByLabel('Email').fill(email)
await p.getByRole('button', { name: 'Next', exact: true }).click()
await p.waitForTimeout(400)
await p.locator('fieldset label').first().click()
await p.getByRole('button', { name: 'Next', exact: true }).click()
await p.waitForTimeout(1500)
console.log('auto-submitted?', (await p.getByRole('status').count()) > 0 ? 'YES (bug)' : 'no')
await p.getByRole('button', { name: 'Submit registration' }).click()
await p.getByRole('status').waitFor({ timeout: 45000 })
console.log('UI result:', (await p.getByRole('status').innerText()).replace(/\s+/g, ' ').slice(0, 200))
await b.close()
