import { Amplify } from 'aws-amplify'
import { generateClient } from 'aws-amplify/data'
import { getAmplifyDataClientConfig } from '@aws-amplify/backend/function/runtime'
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, UpdateCommand } from '@aws-sdk/lib-dynamodb'
// Generated by `ampx sandbox` / `ampx pipeline-deploy`; see README §Backend.
// eslint-disable-next-line import/no-unresolved
import { env } from '$amplify/env/book-test-slot'
import type { Schema } from '../../data/resource'
import { runNotifiers, sendEmail, sendWhatsAppTemplate } from '../shared/notify'

const { resourceConfig, libraryOptions } = await getAmplifyDataClientConfig(env)
Amplify.configure(resourceConfig, libraryOptions)
const client = generateClient<Schema>({ authMode: 'iam' })

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({}))

class SlotFullError extends Error {}

/**
 * Claims one seat on the slot with a single conditional UpdateItem, so two
 * simultaneous registrations can never oversell the same slot.
 */
async function claimSeat(slotId: string) {
  const table = process.env.TEST_SLOT_TABLE
  if (!table) throw new Error('TEST_SLOT_TABLE is not set — see amplify/backend.ts')

  try {
    const res = await ddb.send(
      new UpdateCommand({
        TableName: table,
        Key: { id: slotId },
        UpdateExpression: 'SET booked = if_not_exists(booked, :zero) + :one, updatedAt = :now',
        // `if_not_exists` is only legal in the update expression, not here —
        // DynamoDB rejects it with a ValidationException. A missing `booked`
        // attribute means zero bookings, which is what the OR expresses.
        ConditionExpression:
          'attribute_exists(id) AND (attribute_not_exists(booked) OR booked < #cap) AND (attribute_not_exists(isOpen) OR isOpen = :true)',
        // `capacity` is a DynamoDB reserved word and must be aliased.
        ExpressionAttributeNames: { '#cap': 'capacity' },
        ExpressionAttributeValues: {
          ':zero': 0,
          ':one': 1,
          ':true': true,
          ':now': new Date().toISOString(),
        },
        ReturnValues: 'ALL_NEW',
      })
    )
    return res.Attributes as
      | {
          id: string
          start?: string
          end?: string
          room?: string
          booked: number
          capacity: number
        }
      | undefined
  } catch (err) {
    if (err instanceof Error && err.name === 'ConditionalCheckFailedException') {
      throw new SlotFullError('slot_full')
    }
    throw err
  }
}

async function releaseSeat(slotId: string) {
  const table = process.env.TEST_SLOT_TABLE
  if (!table) return
  await ddb
    .send(
      new UpdateCommand({
        TableName: table,
        Key: { id: slotId },
        UpdateExpression: 'SET booked = booked - :one',
        ConditionExpression: 'booked > :zero',
        ExpressionAttributeValues: { ':one': 1, ':zero': 0 },
      })
    )
    .catch((err: unknown) => console.error('releaseSeat failed', err))
}

export const handler: Schema['bookTestSlot']['functionHandler'] = async (event) => {
  const { registrationId, slotId, locale } = event.arguments

  let slot: Awaited<ReturnType<typeof claimSeat>>
  try {
    slot = await claimSeat(slotId)
  } catch (err) {
    if (err instanceof SlotFullError) return { ok: false, reason: 'slot_full' }
    throw err
  }

  try {
    const { data: registration } = await client.models.Registration.get({ id: registrationId })
    if (!registration) {
      await releaseSeat(slotId)
      return { ok: false, reason: 'registration_not_found' }
    }

    const { data: appointment, errors } = await client.models.TestAppointment.create({
      registrationId,
      slotId,
      slotStart: slot?.start,
      slotEnd: slot?.end,
      room: slot?.room ?? 'Exam room 1',
      status: 'BOOKED',
    })

    if (errors?.length || !appointment) {
      await releaseSeat(slotId)
      console.error('TestAppointment.create failed', errors)
      return { ok: false, reason: 'appointment_failed' }
    }

    await client.models.Registration.update({ id: registrationId, status: 'TEST_SCHEDULED' })

    const when = slot?.start
      ? new Date(slot.start).toISOString().replace('T', ' ').slice(0, 16)
      : '-'

    const results = await runNotifiers({
      email: () =>
        sendEmail(`Test appointment booked — ${registration.name}`, [
          `Name: ${registration.name}`,
          `Phone: ${registration.phone}`,
          `Email: ${registration.email}`,
          `Track: ${registration.trackSlug ?? '-'}`,
          `Slot: ${when} UTC`,
          `Room: ${appointment.room ?? '-'}`,
          `Registration ID: ${registrationId}`,
        ]),
      // Confirmation goes to the candidate's own number.
      whatsapp: () =>
        sendWhatsAppTemplate(
          'WHATSAPP_TEMPLATE_TEST',
          [registration.name, when, appointment.room ?? '-'],
          { to: registration.phone, languageCode: locale === 'en' ? 'en' : 'ar' }
        ),
    })

    return {
      ok: true,
      appointmentId: appointment.id,
      slotStart: slot?.start ?? null,
      slotEnd: slot?.end ?? null,
      room: appointment.room ?? null,
      ...results,
    }
  } catch (err) {
    await releaseSeat(slotId)
    throw err
  }
}
