/**
 * `amplify_outputs.json` is generated by `ampx sandbox` (locally) or by
 * `ampx pipeline-deploy` (Amplify Hosting), and is git-ignored.
 *
 * Anyone who clones the repo before a backend exists still needs `npm run build`
 * and `npm run dev` to work, so this writes a clearly-marked placeholder when the
 * real file is missing. `lib/amplify.ts` detects the placeholder and the public
 * pages fall back to `data/seed-content.ts`; nothing tries to reach AWS.
 *
 * The real file is never overwritten.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const target = join(root, 'amplify_outputs.json')

if (existsSync(target)) {
  // A real file — but is it this project's backend? The Todo starter's file
  // has the same shape and would fail every query at request time.
  try {
    const outputs = JSON.parse(readFileSync(target, 'utf8'))
    const models = Object.keys(outputs?.data?.model_introspection?.models ?? {})
    if (!outputs._placeholder && outputs?.data?.url && !models.includes('Track')) {
      console.warn(
        [
          '[qte] amplify_outputs.json describes a different backend',
          `      (models: ${models.join(', ') || 'none'}; expected Track, Registration, …).`,
          '      The site renders from seed content and forms stay disabled until this',
          "      repo's amplify/ folder is deployed: `npx ampx sandbox` or Amplify Hosting.",
        ].join('\n')
      )
    }
  } catch {
    /* unreadable file — let the build surface it */
  }
  process.exit(0)
}

writeFileSync(
  target,
  `${JSON.stringify({ version: '1.3', _placeholder: true }, null, 2)}\n`,
  'utf8'
)

console.warn(
  '[qte] amplify_outputs.json was missing — wrote a placeholder.\n' +
    '      Run `npx ampx sandbox` (or deploy the backend) to generate the real one.\n' +
    '      Until then the site renders from data/seed-content.ts and forms are disabled.'
)
