/**
 * `amplify_outputs.json` is generated by `ampx sandbox` (locally) or by
 * `ampx pipeline-deploy` (Amplify Hosting), and is git-ignored.
 *
 * Anyone who clones the repo before a backend exists still needs `npm run build`
 * and `npm run dev` to work, so this writes a clearly-marked placeholder when the
 * real file is missing. `lib/amplify.ts` detects the placeholder and the public
 * pages fall back to `data/seed-content.ts`; nothing tries to reach AWS.
 *
 * The real file is never overwritten.
 */
import { existsSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const target = join(root, 'amplify_outputs.json')

if (existsSync(target)) {
  process.exit(0)
}

writeFileSync(
  target,
  `${JSON.stringify({ version: '1.3', _placeholder: true }, null, 2)}\n`,
  'utf8'
)

console.warn(
  '[qte] amplify_outputs.json was missing — wrote a placeholder.\n' +
    '      Run `npx ampx sandbox` (or deploy the backend) to generate the real one.\n' +
    '      Until then the site renders from data/seed-content.ts and forms are disabled.'
)
